<?php
/**
 * Created by PhpStorm.
 * User: minhphuc
 * Date: 06/01/2018
 * Time: 09:48
 */

namespace App\Controller;


class CustomersController extends AppController {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('isPage', 'customers');
        $this->loadModel('Posts');
        $this->loadModel('Menus');
    }

    public function index() {
        /** @var \App\Model\Entity\Post $post */
        $post = $this->Posts->find()
            ->where([
                'menu_id' => 4,
            ])
            ->first();

        /** @var \App\Model\Entity\Menu $menu */
        $menu = $this->Menus->find()
            ->where([
                'id' => $post->menu_id,
            ])
            ->first();

        $this->set(compact('post', 'menu'));
    }

    public function edit($slug) {}

}
