<?php
/**
 * Created by PhpStorm.
 * User: minhphuc
 * Date: 06/01/2018
 * Time: 09:48
 */

namespace App\Controller;


class CustomersController extends AppController {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('isPage', 'customers');
        $this->loadModel('Posts');
        $this->loadModel('Groups');
    }

    public function index() {
        /** @var \App\Model\Entity\Post $post */
        $post = $this->Posts->find()
            ->where([
                'group_id' => 6,
                'delete_flag' => false
            ])
            ->first();

        /** @var \App\Model\Entity\Group $group */
        $group = $this->Groups->find()
            ->where([
                'id' => $post->group_id,
                'delete_flag' => false
            ])
            ->first();

        $title = 'Khách hàng - Thiết kế kiến trúc, nội thất... - + P A H - pah.com.vn';

        $this->set(compact('post', 'group', 'title'));
    }

    public function edit($slug) {}

}
