<?php

namespace PahAdmin\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\I18n\Date;
use Cake\I18n\Time;

/**
 * Class AdminController
 * @package PahAdmin\Controller
 *
 * @property \App\Model\Table\PostsTable $Posts
 * @property \App\Model\Table\ContactsTable $Contacts
 * @property \App\Model\Table\BannersTable $Banners
 * @property \App\Model\Table\MenusTable $Menus
 */
class AdminController extends Controller
{
    /**
     * @throws \Exception
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Time::setToStringFormat('M/d/Y H:m');
        Date::setToStringFormat('M/d/Y');
        $this->loadComponent('Csrf');
        $this->loadComponent('Flash');

        $this->viewBuilder()->setClassName('PahAdmin.Admin');

        /** Existing code */
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Auth', [
            /** Added this line */
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login',
                'plugin' => 'PahAdmin'
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'login',
                'plugin' => 'PahAdmin'
            ],
            'loginRedirect' => [
                'controller' => 'Posts',
                'action' => 'index',
                'plugin' => 'PahAdmin'
            ],
            'authError' => 'Did you really think you are allowed to see that?'
        ]);

        $this->loadModel('Menus');

        $parentCategories = $this->Menus->find('treeList', [
            'keyPath' => 'id',
            'valuePath' => 'name',
            'spacer' => ' * '
        ])
            ->orderAsc('lft')
            ->toArray();

        $option = [
            '' => 'No parent menu',
        ];
        $option += $parentCategories;

        $this->set(compact('option',  'parentCategories'));

    }

    /**
     * @param Event $event
     * @return void
     */
    public function beforeRender(Event $event) {
        /** Login check */
        if ($this->Auth->user()) {
            $this->set('LoggedIn', true);
        } else {
            $this->set('LoggedIn', false);
        }
    }
}
