<?php

namespace PahAdmin\Controller;

use Cake\Network\Exception\NotFoundException;
use Cake\Validation\Validator;

/**
 * Created by PhpStorm.
 * User: minhphuc
 * Date: 04/01/2018
 * Time: 13:59
 */

class ContactsController extends AdminController {

    protected $contact_key = 'contact';
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Contacts');
    }

    /**
     * @param null $id
     */
    public function update($id = null) {
        /** @var \App\Model\Entity\Contact $contact */

        $contact_key = $this->contact_key;

        $id = intval($id);

        $contact = $this->Contacts->find()
            ->where([
                'id' => $id
            ])
            ->firstOrFail();

        if ($this->request->is(['patch', 'post', 'put'])) {

            $data = $this->request->getData();

            $validator = new Validator();

            $validator
                ->requirePresence('image_uri')
                ->requirePresence('company')
                ->allowEmpty('company')
                ->requirePresence('address')
                ->allowEmpty('address')
                ->requirePresence('fax')
                ->allowEmpty('fax')
                ->requirePresence('tax_code')
                ->allowEmpty('tax_code')
                ->requirePresence('email')
                ->allowEmpty('email')
                ->requirePresence('hotline')
                ->allowEmpty('hotline')
                ->requirePresence('tel')
                ->allowEmpty('tel');

            $errors = $validator->errors($this->request->getData());

            if ($errors) {
                throw new NotFoundException('Invalid request!');
            }

            $contact->uri = $data['image_uri'];
            $contact->company = $data['company'];
            $contact->author = $this->Auth->user('first_name') . ' ' . $this->Auth->user('last_name');
            $contact->address = $data['address'];
            $contact->tel = $data['tel'];
            $contact->fax = $data['fax'];
            $contact->tax_code = $data['tax_code'];
            $contact->email = $data['email'];
            $contact->hotline = $data['hotline'];
            $contact->website = $data['website'];

            if ($this->Contacts->save($contact)) {
                $this->Flash->success(__('The user has been saved.'), ['key' => 'contact_key']);
                $this->redirect($this->referer());
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'), ['key' => 'contact_key']);
        }
        $this->set(compact('contact', 'contact_key'));
    }
}
