<?php
namespace PahAdmin\Controller;

use App\Controller\API\StringAPI;
use Cake\Network\Exception\NotFoundException;
use Cake\Validation\Validator;

/**
 * Class GroupController
 * @property \App\Model\Table\GroupsTable $Groups
 * @package App\Controller
 */
class GroupsController extends AdminController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Groups');
    }

    public function index() {}

    public function datatables() {
        $this->response = $this->response->withHeader('Content-Type', 'application/json');

        $params = $this->_parse_datatables_params();

        /** @var \App\Model\Entity\Group[] $groups */
        $groups_query = $this->Groups->find();

        $params['recordsFiltered'] = $params['recordsTotal'] = $groups_query->count();

        $groups_query->orderDesc('created')
            ->where([
                'title LIKE' => '%' . $params['keyword'] . '%',
                'delete_flag' => 0
            ])
            ->limit($params['length'])->offset($params['start']);

        $groups = $groups_query->toArray();

        $params['data'] = $groups;

        $this->response = $this->response->withStringBody( json_encode( $params ) );
        return $this->response;
    }

    /**
     * Edit method
     *
     * @param string|null $id Group id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null) {
        $request = $this->request;
        /** @var \App\Model\Entity\Group $group */
        if ( $id ) {
            $group = $this->Groups->find()
                ->where([
                    'id' => $id,
                    'delete_flag' => 0
                ])
                ->first();
        } else {
            $group = $this->Groups->newEntity();
        }

        $this->set(compact('group'));

        if($this->request->is(['post', 'put', 'patch'])) {
            $data = $request->getData();

            // Data processing
            $validator = new Validator();

            $validator
                ->requirePresence('title')
                ->notEmpty('title');

            $errors = $validator->errors($this->request->getData());

            if($errors) {
                throw new NotFoundException('Invalid request!');
            }
            $group->title = $data['title'];
            $group->slug = StringAPI::convertToAscii($data['title']);

            if ($this->Groups->save($group)) {
                $this->Flash->success(__('The user has been saved.'), ['key' => 'groups_key']);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'), ['key' => 'groups_key']);
        }
    }

    /**
     * @return array
     */
    protected function _parse_datatables_params() {
        $params = array(
            'start' => floor($this->request->getQuery('start')),
            'length' => floor($this->request->getQuery('length')),
            'draw' => floor($this->request->getQuery('draw')),
        );

        if($params['length'] > 200) {
            $params['length'] = 50;
        }

        $search = $this->request->getQuery('search'); //value: value search, regex: true/false
        $order = $this->request->getQuery('order');

        $params['direction'] = $params['column_ordered'] = false;
        if($order && isset($order[0])) {
            if(isset($order[0]['column'])) {
                $params['column_ordered'] = $order[0]['column']; // Direction, not need to validate
            }

            if(isset($order[0]['dir'])) {
                $params['direction'] = $order[0]['dir']; // Direction, not need to validate
            }
        };

        $params['keyword'] = false;
        if(isset($search['value']) && $search['value'] != "" && strlen($search['value']) < 250) {
            $params['keyword'] = $search['value'];
        };

        return $params;
    }

    /**
     * @param null $id
     * @return string
     */
    public function delete($id = null)
    {
        $this->response = $this->response->withType('application/json');
        if($this->request->is(['post', 'delete'])) {
            /** @var \App\Model\Entity\Group $group */
            $group = $this->Groups->find()
                ->where([
                    'id' => intval($id)
                ])
                ->first();

            $group->delete_flag = 1;

            if ($this->Groups->save($group)) {
                $this->response = $this->response->withStringBody(json_encode([
                    'status' => 200
                ]));

                return $this->response;
            }
        }

        $this->response = $this->response->withStringBody(json_encode([
            'status' => 201,
            'message' => 'Invalid request'
        ]));

        return $this->response;
    }
}
