<?php

namespace PahAdmin\Controller;
use Cake\Validation\Validation;

/**
 * Class UsersController
 * @property \App\Model\Table\UsersTable $User
 * @package PahAdmin\Controller
 */
class UsersController extends AdminController {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('login');
    }

    /**
     * @return \Cake\Http\Response|null
     */
    public function login() {
        if ($this->request->is('post')) {
            $data = $this->request->getData();
            if (Validation::email($data['username'])) {
                $this->Auth->setConfig('authenticate', [
                    'Form' => [
                        'fields' => ['username' => 'email']
                    ]
                ]);
                $this->Auth->constructAuthenticate();
                $this->request = $this->request->withData('email', $data['username']);
                unset($data['username']);
            }
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Username or password is incorrect'));
        }
    }

    /**
     * @return \Cake\Http\Response|null
     */
    public function logout() {
        $this->Flash->success('You are now logged out.');
        return $this->redirect($this->Auth->logout());
    }
}
